@baseurl = http://localhost:3000

// Get all tickets
GET {{baseurl}}/tickets

###

// Create a ticket
POST {{baseurl}}/tickets
Content-Type: application/json

{
  "ticket": {
    "client": "foo",
    "issue": "the test is not working",
    "status": "open",
    "deadline": "2023-02-15"
  }
}

###

// Update a single ticket
PUT {{baseurl}}/tickets/64a6f4ffbfdd0118007d04c6
Content-Type: application/json

{
  "ticket": {
    "client": "foo",
    "issue": "the test was fixed",
    "status": "closed",
    "deadline": "2023-02-15"
  }
}