// Get all tickets
GET http://localhost:3000/tickets

// Create a ticket
POST http://localhost:3000/tickets HTTP/1.1
Content-Type: "application/json"

{
  "client": "foo",
  "issue": "the test is not working",
  "status": "open",
  "deadline": "15/02/2023"
}

// Update a single ticket
PUT http://localhost:3000/tickets/1 HTTP/1.1
Content-Type: "application/json"

{
  "client": "foo",
  "issue": "the test was fixed",
  "status": "close",
  "deadline": "15/02/2023"
}