@baseurl = http://localhost:3000

// Get all tickets
GET {{baseurl}}/tickets

###

// Create a ticket
POST {{baseurl}}/tickets
Content-Type: application/json

{
  "ticket": {
    "client": "foo",
    "issue": "the test is not working",
    "status": "open",
    "deadline": "2023-07-06"
  }
}

###

// Create a ticket, with invalid data
POST {{baseurl}}/tickets
Content-Type: application/json

{ }

###

// Update a single ticket
PUT {{baseurl}}/tickets/64a7122f789b2b212db69bac
Content-Type: application/json

{
  "ticket": {
    "status": "closed"
  }
}